[[redirects]]
  from = "/profile"
  to = "/"
  query = {path = "profile"}

[[redirects]]
  from = "/signin"
  to = "/"
  query = {path = "signin"}

[[redirects]]
  from = "/signup"
  to = "/"
  query = {path = "signup"}